version: "2"
services:
    web:
        build: ./web-image
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - default
        hostname: webdemo.nateyang1999.works
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8002:80
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}